# MetaboHUB - 2014

webServicesRest = PeakForest_WebServices
softwareRequirementSpecification = PeakForest_Software_Requirement_Specification
WebAppInstall = PeakForest_WebApp_Install

all: $(webServicesRest).pdf $(softwareRequirementSpecification).pdf $(WebAppInstall).pdf
# (next all) $(softwareRequirementSpecification).pdf

rest: $(webServicesRest).pdf
srs: $(softwareRequirementSpecification).pdf
webapp: $(WebAppInstall).pdf

$(webServicesRest).pdf : $(webServicesRest).tex vc.tex
	while (pdflatex $(webServicesRest) ; \
	grep -q "Rerun to get cross" $(webServicesRest).log ) do true ; \
	done
	while (pdflatex $(webServicesRest) ; \
	grep -q "Rerun to get cross" $(webServicesRest).log ) do true ; \
	done
	@rm -f *.aux *.lof *.log *.log *.toc *.out *.synctex.gz
#	@mv PeakForest_WebServices.pdf PeakForest_WebServices.pdf

$(softwareRequirementSpecification).pdf : $(softwareRequirementSpecification).tex vc.tex 
	while (pdflatex $(softwareRequirementSpecification) ; \
	grep -q "Rerun to get cross" $(softwareRequirementSpecification).log ) do true ; \
	done
	while (pdflatex $(softwareRequirementSpecification) ; \
	grep -q "Rerun to get cross" $(softwareRequirementSpecification).log ) do true ; \
	done
	@rm -f *.aux *.lof *.log *.log *.toc *.out *.synctex.gz
#	@mv PeakForest_Software_Requirement_Specification.pdf PeakForest_Software_Requirement_Specification.pdf

$(WebAppInstall).pdf : $(WebAppInstall).tex vc.tex 
	while (pdflatex $(WebAppInstall) ; \
	grep -q "Rerun to get cross" $(WebAppInstall).log ) do true ; \
	done
	while (pdflatex $(WebAppInstall) ; \
	grep -q "Rerun to get cross" $(WebAppInstall).log ) do true ; \
	done
	@rm -f *.aux *.lof *.log *.log *.toc *.out *.synctex.gz
#	@mv PeakForest_WebApp_Install.pdf PeakForest_WebApp_Install.pdf

vc.tex: .git/logs/HEAD
	echo "%%% This file is generated by Makefile." > vc.tex
	echo "%%% Do not edit this file!\n%%%" >> vc.tex
	git log -1 --format="format:\
		\\gdef\\GITAbrHash{%h}\
		\\gdef\\GITAuthorDate{%ad}\
		\\gdef\\GITAuthorName{%an}" >> vc.tex

clean:
	@rm -f *.aux *.lof *.log *.log *.toc *.out *.pdf *.synctex.gz

