# MetaboHUB - 2019

# MAMA
mamaWebServicesRest = MAMA_WebServices

all: $(mamaWebServicesRest).pdf

mama-rest: $(mamaWebServicesRest).pdf

$(mamaWebServicesRest).pdf : $(mamaWebServicesRest).tex vc.tex
	while (pdflatex $(mamaWebServicesRest) ; \
	grep -q "Rerun to get cross" $(mamaWebServicesRest).log ) do true ; \
	done
	while (pdflatex $(mamaWebServicesRest) ; \
	grep -q "Rerun to get cross" $(mamaWebServicesRest).log ) do true ; \
	done
	@rm -f *.aux *.lof *.log *.log *.toc *.out *.synctex.gz

vc.tex: .git/logs/HEAD
	echo "%%% This file is generated by Makefile." > vc.tex
	echo "%%% Do not edit this file!\n%%%" >> vc.tex
	git log -1 --format="format:\
		\\gdef\\GITAbrHash{%h}\
		\\gdef\\GITAuthorDate{%ad}\
		\\gdef\\GITAuthorName{%an}" >> vc.tex

clean:
	@rm -f *.aux *.lof *.log *.log *.toc *.out *.pdf *.synctex.gz

