# MetaboHUB - 2014

webServicesRest = Spectral_Database_WebServices
# latexfileCharteGit = charte_developpement_git
# 
# all: $(webServicesRest).pdf $(latexfileCharteGit).pdf
# 
rest: $(webServicesRest).pdf
# git: $(latexfileCharteGit).pdf

$(webServicesRest).pdf : $(webServicesRest).tex vc.tex
	while (pdflatex $(webServicesRest) ; \
	grep -q "Rerun to get cross" $(webServicesRest).log ) do true ; \
	done
	while (pdflatex $(webServicesRest) ; \
	grep -q "Rerun to get cross" $(webServicesRest).log ) do true ; \
	done
	@rm -f *.aux *.lof *.log *.log *.toc *.out

# $(latexfileCharteGit).pdf : $(latexfileCharteGit).tex vc.tex 
# 	while (pdflatex $(latexfileCharteGit) ; \
# 	grep -q "Rerun to get cross" $(latexfileCharteGit).log ) do true ; \
# 	done
# 	while (pdflatex $(latexfileCharteGit) ; \
# 	grep -q "Rerun to get cross" $(latexfileCharteGit).log ) do true ; \
# 	done
# 	@rm -f *.aux *.lof *.log *.log *.toc *.out

vc.tex: .git/logs/HEAD
	echo "%%% This file is generated by Makefile." > vc.tex
	echo "%%% Do not edit this file!\n%%%" >> vc.tex
	git log -1 --format="format:\
		\\gdef\\GITAbrHash{%h}\
		\\gdef\\GITAuthorDate{%ad}\
		\\gdef\\GITAuthorName{%an}" >> vc.tex

clean:
	@rm -f *.aux *.lof *.log *.log *.toc *.out *.pdf

